version: '2.2'
services:
  cpp-orderbook-bench:
    build: .
    container_name: cpp-orderbook-bench
    cpus: 1
    privileged: true # for bench only, to avoid kernel mitigations override
    cpuset: "1"
    command:
      - "-duration"
      - "30"
      - "-start-after"
      - "60"
      - "-n"
      - "throughput"
